#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/wxprec.h>
#include <memory>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panel1OnPaint( wxPaintEvent& event );
		void Button_SaveToFileOnButtonClick( wxCommandEvent& event );
		void CheckBox_LoadBananOnCheckBox( wxCommandEvent& event );
		void ScrollBar_MoveBananOnScroll( wxScrollEvent& event );
		void Button_StarColorOnButtonClick( wxCommandEvent& event );
		void TextCtrl_WriteOnText( wxCommandEvent& event );
		void Choice_ElementOnChoice( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members




};

#endif // __GUIMyFrame1__
