#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <FreeImage.h>
#include <wx/dcclient.h>
#include <wx/image.h>
#include <CImg.h>
#include <wx/timer.h>
#define PI 3.14159265359

using namespace cimg_library;

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1, public wxTimer
{
	protected:
		// Handlers for MyFrame1 events.
		void wxButton_ReadFile( wxCommandEvent& event );
		void wxButton_Censure( wxCommandEvent& event );
		void wxButton_Erode( wxCommandEvent& event );
		void wxCheckBox_StartAnimation( wxCommandEvent& event );
		void ChangePhotoSize( wxSizeEvent& event );
		void wxPanel_Repaint( wxUpdateUIEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void Draw();

		CImg<unsigned char> OrginalPhoto, EditedPhoto;
		std::vector<wxImage> AnimationArray;
		int width = 0, height = 0;
		void Notify() override;
};

#endif // __GUIMyFrame1__
