#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/timer.h>
#include <cmath>
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <memory>
#include <Windows.h>

#define PI 3.14159265359

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1, public wxTimer
{
	protected:
		// Handlers for MyFrame1 events.
		void wxPanel_UpdateUI( wxUpdateUIEvent& event );
		void wxText_ChangeA( wxCommandEvent& event );
		void wxText_ChangeB( wxCommandEvent& event );
		void wxText_ChangeC( wxCommandEvent& event );
		void wxText_ChangeD( wxCommandEvent& event );
		void wxText_ChangeE( wxCommandEvent& event );
		void wxText_ChangeF( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void Notify() override;
		void Draw();

	private:
		double A, B, C, D, E, F;
		float time;
		wxClientDC dc;
};

#endif // __GUIMyFrame1__
