#ifndef __majaMyFrame1__
#define __majaMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "maja.h"

//// end generated include

/** Implementing MyFrame1 */
class majaMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events.
	void Na_klik(wxCommandEvent& event);
	void Na_wpisanie(wxCommandEvent& event);
	void Na_ruch(wxScrollEvent& event);
	void Na_wybor(wxCommandEvent& event);
public:
	/** Constructor */
	majaMyFrame1(wxWindow* parent);
	//// end generated class members
	int SquarePosition;
};

#endif // __majaMyFrame1__